### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by luporl** [legoater/pnv-test#3]
The following line of code causes the decrementer test to fail to build, because MSR_LE isn't defined anywhere.

https://github.com/legoater/pnv-test/blob/d87af12873925bffddd53afaa62e7746affb7bc4/decrementer/head.S#L21

**Comment by legoater** [comment]
There is a typo in:
```
#define MSR 0x1
#define MSR_ENDIAN MSR_LE
```
should be : 
```
#define MSR_LE 0x1
#define MSR_ENDIAN MSR_LE
```

**Comment by luporl** [comment]
Fixed in latest version of main.
